name: Terraform flow 
on:
  push:
    branches: 
      - main
    
env:      
  AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9

      - name: Deploy using Terraform
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_KEY }}
          terraform init
      - name: Terraform flow
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_KEY }}
          eval 'ssh-agent -s'
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          terraform fmt
          terraform validate
          terraform plan